name: Build NodeJS Containers

on:
    push:
        paths:
            - "**/Dockerfile"
            - genMatrix.js

    pull_request:
        paths:
            - "**/Dockerfile"
            - genMatrix.js

jobs:
    genMatrix:
        name: Generate Matrix
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Calculate Differences
              id: diff
              uses: tj-actions/changed-files@v44
              with:
                json: true
                escape_json: false
            
            - name: Generate Matrix
              uses: actions/github-script@v7
              id: generator
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                script: |
                  const script = require(`${process.env.GITHUB_WORKSPACE}/genMatrix.js`)
                  return script(
                      ${{ steps.diff.outputs.added_files }},
                      ${{ steps.diff.outputs.modified_files }},
                      ${{ steps.diff.outputs.renamed_files }},
                  );
        outputs:
            matrix: ${{ steps.generator.outputs.result }}
    
    build:
        if: ${{ fromJson(needs.genMatrix.outputs.matrix) }}
        needs: genMatrix
        name: build
        runs-on: ubuntu-latest
        timeout-minutes: 60
        strategy:
            fail-fast: false
            matrix: ${{ fromJson(needs.genMatrix.outputs.matrix) }}

        steps:
            - name: Node Version
              uses: actions/github-script@v7
              id: short-version
              with:
                result-encoding: string
                script: return "${{ matrix.version }}".split('.')[0]
          
            - name: Checkout
              uses: actions/checkout@v4

            - name: GHCR Authenticate
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          
            - name: Build Image
              run: |
                docker build \
                    --file ./${{ steps.short-version.outputs.result }}/${{ matrix.variant }}/Dockerfile \
                    --tag ghcr.io/SkyBlueHoldings/node:${{ matrix.version }}-${{ matrix.variant }} \
                    --label "org.opencontainers.image.source=https://github.com/SkyBlueHoldings/NodeDocker" \
                    --label "org.opencontainers.image.vendor=Sky Blue Holdings (EMEA) Limited" \
                    .

            - name: Push Image
              run: |
                docker push ghcr.io/SkyBlueHoldings/node:${{ matrix.version }}-${{ matrix.variant }}